name: Publish to TestPyPI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  publish-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Install dependencies
      run: uv sync --dev
    
    - name: Run tests
      run: |
        uv run pytest tests/ \
          --cov=src/mygh \
          --cov-fail-under=95
    
    - name: Update version for TestPyPI
      run: |
        # Generate a development version based on git commit
        DEV_VERSION="0.1.0.dev$(date +%Y%m%d%H%M%S)+$(git rev-parse --short HEAD)"
        echo "Building development version: $DEV_VERSION"
        sed -i "s/version = \"0.1.0\"/version = \"$DEV_VERSION\"/" pyproject.toml
    
    - name: Build package
      run: uv build
    
    - name: Check package
      run: |
        uv add --dev twine
        uv run twine check dist/*
    
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        print: true
        skip-existing: true